In [1]:
from importlib.resources import files

import pandas as pd
import numpy as np

In [10]:
!curl https://www.kaggle.com/api/v1/datasets/download/ssssws/chocolate-sales-dataset-2023-2024 -L -o chocolat-sales.zip

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 23.2M  100 23.2M    0     0  9429k      0  0:00:02  0:00:02 --:--:-- 14.2M

In [12]:
!unzip chocolat-sales.zip

Archive:  chocolat-sales.zip
  inflating: calendar.csv
  inflating: customers.csv
  inflating: products.csv
  inflating: sales.csv
  inflating: stores.csv

In [3]:
pd.read_csv("pandas_tutorial_read.csv")

       ins     type_entity           entity      period  value
0     3000          Région         Wallonie  01/01/2019  215.0
1    20002        Province   Brabant Wallon  01/01/2019  367.9
2    25000  Arrondissement         Nivelles  01/01/2019  367.9
3    25005         Commune      Beauvechain  01/01/2019  187.8
4    25014         Commune  Braine-l'Alleud  01/01/2019  764.8
..     ...             ...              ...         ...    ...
286  93018         Commune          Doische  01/01/2019   35.6
287  93022         Commune        Florennes  01/01/2019   84.3
288  93056         Commune    Philippeville  01/01/2019   59.0
289  93088         Commune         Walcourt  01/01/2019  149.1
290  93090         Commune        Viroinval  01/01/2019   46.7

[291 rows x 5 columns]

In [13]:
df = pd.read_csv("pandas_tutorial_read.csv")

df

       ins     type_entity           entity      period  value
0     3000          Région         Wallonie  01/01/2019  215.0
1    20002        Province   Brabant Wallon  01/01/2019  367.9
2    25000  Arrondissement         Nivelles  01/01/2019  367.9
3    25005         Commune      Beauvechain  01/01/2019  187.8
4    25014         Commune  Braine-l'Alleud  01/01/2019  764.8
..     ...             ...              ...         ...    ...
286  93018         Commune          Doische  01/01/2019   35.6
287  93022         Commune        Florennes  01/01/2019   84.3
288  93056         Commune    Philippeville  01/01/2019   59.0
289  93088         Commune         Walcourt  01/01/2019  149.1
290  93090         Commune        Viroinval  01/01/2019   46.7

[291 rows x 5 columns]

In [14]:
type(df)

pandas.DataFrame

In [15]:
df[["entity"]]

              entity
0           Wallonie
1     Brabant Wallon
2           Nivelles
3        Beauvechain
4    Braine-l'Alleud
..               ...
286          Doische
287        Florennes
288    Philippeville
289         Walcourt
290        Viroinval

[291 rows x 1 columns]

In [17]:
df.entity.apply(lambda row: str.upper(row))

0             WALLONIE
1       BRABANT WALLON
2             NIVELLES
3          BEAUVECHAIN
4      BRAINE-L'ALLEUD
            ...
286            DOISCHE
287          FLORENNES
288      PHILIPPEVILLE
289           WALCOURT
290          VIROINVAL
Name: entity, Length: 291, dtype: str

In [18]:
df.head(15)

      ins     type_entity               entity      period  value
0    3000          Région             Wallonie  01/01/2019  215.0
1   20002        Province       Brabant Wallon  01/01/2019  367.9
2   25000  Arrondissement             Nivelles  01/01/2019  367.9
3   25005         Commune          Beauvechain  01/01/2019  187.8
4   25014         Commune      Braine-l'Alleud  01/01/2019  764.8
5   25015         Commune    Braine-le-Château  01/01/2019  463.7
6   25018         Commune     Chaumont-Gistoux  01/01/2019  244.1
7   25023         Commune  Court-Saint-Étienne  01/01/2019  392.2
8   25031         Commune              Genappe  01/01/2019  170.7
9   25037         Commune         Grez-Doiceau  01/01/2019  246.1
10  25043         Commune              Incourt  01/01/2019  141.0
11  25044         Commune                Ittre  01/01/2019  196.7
12  25048         Commune             Jodoigne  01/01/2019  191.5
13  25050         Commune             La Hulpe  01/01/2019  473.3
14  25068         Commune   Mont-Saint-Guibert  01/01/2019  414.8

In [19]:
df.tail(15)

       ins     type_entity              entity      period  value
276  92101         Commune       Profondeville  01/01/2019  242.5
277  92114         Commune           Sombreffe  01/01/2019  235.1
278  92137         Commune         Sambreville  01/01/2019  825.7
279  92138         Commune          Fernelmont  01/01/2019  122.0
280  92140         Commune  Jemeppe-sur-Sambre  01/01/2019  408.5
281  92141         Commune          La Bruyère  01/01/2019  174.9
282  92142         Commune            Gembloux  01/01/2019  269.7
283  93000  Arrondissement       Philippeville  01/01/2019   72.9
284  93010         Commune         Cerfontaine  01/01/2019   59.0
285  93014         Commune              Couvin  01/01/2019   66.4
286  93018         Commune             Doische  01/01/2019   35.6
287  93022         Commune           Florennes  01/01/2019   84.3
288  93056         Commune       Philippeville  01/01/2019   59.0
289  93088         Commune            Walcourt  01/01/2019  149.1
290  93090         Commune           Viroinval  01/01/2019   46.7

In [20]:
df.tail(-2)

       ins     type_entity             entity      period  value
2    25000  Arrondissement           Nivelles  01/01/2019  367.9
3    25005         Commune        Beauvechain  01/01/2019  187.8
4    25014         Commune    Braine-l'Alleud  01/01/2019  764.8
5    25015         Commune  Braine-le-Château  01/01/2019  463.7
6    25018         Commune   Chaumont-Gistoux  01/01/2019  244.1
..     ...             ...                ...         ...    ...
286  93018         Commune            Doische  01/01/2019   35.6
287  93022         Commune          Florennes  01/01/2019   84.3
288  93056         Commune      Philippeville  01/01/2019   59.0
289  93088         Commune           Walcourt  01/01/2019  149.1
290  93090         Commune          Viroinval  01/01/2019   46.7

[289 rows x 5 columns]

In [21]:
df.shape

(291, 5)

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 291 entries, 0 to 290
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ins          291 non-null    int64
 1   type_entity  291 non-null    str
 2   entity       291 non-null    str
 3   period       291 non-null    str
 4   value        291 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 11.5 KB

In [23]:
df.columns

Index(['ins', 'type_entity', 'entity', 'period', 'value'], dtype='str')

In [24]:
df[['ins']].shape

(291, 1)

In [25]:
df['ins']

0       3000
1      20002
2      25000
3      25005
4      25014
       ...
286    93018
287    93022
288    93056
289    93088
290    93090
Name: ins, Length: 291, dtype: int64

In [26]:
df['ins'].dtype

dtype('int64')

In [27]:
isolated_col = ['ins', 'entity']

df[isolated_col]

       ins           entity
0     3000         Wallonie
1    20002   Brabant Wallon
2    25000         Nivelles
3    25005      Beauvechain
4    25014  Braine-l'Alleud
..     ...              ...
286  93018          Doische
287  93022        Florennes
288  93056    Philippeville
289  93088         Walcourt
290  93090        Viroinval

[291 rows x 2 columns]

In [28]:
df_copy = df.copy()

In [29]:
df.select_dtypes(include=['int64'])

       ins
0     3000
1    20002
2    25000
3    25005
4    25014
..     ...
286  93018
287  93022
288  93056
289  93088
290  93090

[291 rows x 1 columns]

In [30]:
df.select_dtypes(include=['int64']).columns

Index(['ins'], dtype='str')

In [32]:
df.ins.max()

np.int64(93090)

In [34]:
df.entity.value_counts()

entity
Soignies       3
La Louvière    3
Liège          3
Namur          3
Nivelles       2
              ..
Couvin         1
Doische        1
Florennes      1
Walcourt       1
Viroinval      1
Name: count, Length: 267, dtype: int64

In [35]:
df.entity.unique()

<StringArray>
[           'Wallonie',      'Brabant Wallon',            'Nivelles',
         'Beauvechain',     'Braine-l'Alleud',   'Braine-le-Château',
    'Chaumont-Gistoux', 'Court-Saint-Étienne',             'Genappe',
        'Grez-Doiceau',
 ...
  'Jemeppe-sur-Sambre',          'La Bruyère',            'Gembloux',
       'Philippeville',         'Cerfontaine',              'Couvin',
             'Doische',           'Florennes',            'Walcourt',
           'Viroinval']
Length: 267, dtype: str

In [37]:
df.entity.unique().max()

'Étalle'

In [38]:
df.ins.unique().std()

np.float64(19313.462012835713)

In [39]:
df.ins.unique().mean()

np.float64(64158.17361111111)

In [43]:
df['ins'].idxmax()

290

# ILOC

In [44]:
df.iloc[65: 151]

       ins type_entity          entity      period   value
65   53068     Commune       Quiévrain  01/01/2019   317.6
66   53070     Commune  Saint-Ghislain  01/01/2019   330.3
67   53082     Commune     Colfontaine  01/01/2019  1514.1
68   53083     Commune       Honnelles  01/01/2019   116.4
69   53084     Commune           Quévy  01/01/2019   124.4
..     ...         ...             ...         ...     ...
146  62099     Commune        Soumagne  01/01/2019   622.4
147  62100     Commune        Sprimont  01/01/2019   197.4
148  62108     Commune            Visé  01/01/2019   647.3
149  62118     Commune  Grâce-Hollogne  01/01/2019   663.3
150  62119     Commune          Blegny  01/01/2019   509.8

[86 rows x 5 columns]

In [45]:
df.iloc[0:2, 0:3]

     ins type_entity          entity
0   3000      Région        Wallonie
1  20002    Province  Brabant Wallon

In [47]:
df.loc[0:2, 'ins':'entity']

     ins     type_entity          entity
0   3000          Région        Wallonie
1  20002        Province  Brabant Wallon
2  25000  Arrondissement        Nivelles

In [48]:
df.iloc[0:3, [2, 0, 3]]

           entity    ins      period
0        Wallonie   3000  01/01/2019
1  Brabant Wallon  20002  01/01/2019
2        Nivelles  25000  01/01/2019

In [58]:
df.loc[[3, 55, 96], ['entity', 'value', 'period']]

              entity  value      period
3        Beauvechain  187.8  01/01/2019
55  Les Bons Villers  220.0  01/01/2019
96          Péruwelz  281.2  01/01/2019

In [50]:
df['entity'].sort_values(ascending=False)

240            Étalle
217            Érezée
269           Éghezée
75        Écaussinnes
263             Yvoir
            ...
79          Anderlues
267           Andenne
155           Amblève
112              Amay
54     Aiseau-Presles
Name: entity, Length: 291, dtype: str

In [51]:
filter_mask = (df['entity'] == "Soignies")

df.loc[filter_mask]

      ins     type_entity    entity      period  value
70  55000  Arrondissement  Soignies  01/01/2019  292.3
71  55000  Arrondissement  Soignies  01/01/2019  292.3
74  55040         Commune  Soignies  01/01/2019  251.8

In [52]:
df[df['entity'] == "Soignies"]

      ins     type_entity    entity      period  value
70  55000  Arrondissement  Soignies  01/01/2019  292.3
71  55000  Arrondissement  Soignies  01/01/2019  292.3
74  55040         Commune  Soignies  01/01/2019  251.8

In [57]:
df[df['value'] > 1000].head()

      ins type_entity      entity      period   value
17  25091     Commune   Rixensart  01/01/2019  1284.6
20  25110     Commune    Waterloo  01/01/2019  1422.2
45  52011     Commune   Charleroi  01/01/2019  1964.7
46  52012     Commune    Châtelet  01/01/2019  1312.2
48  52018     Commune  Farciennes  01/01/2019  1091.4

In [55]:
df.iloc[[df['value'].idxmax()]]

       ins type_entity         entity      period   value
144  62093     Commune  Saint-Nicolas  01/01/2019  3518.6

In [60]:
df.iloc[[df['value'].idxmax()]]['ins']

144    62093
Name: ins, dtype: int64

In [59]:
df.iloc[25, 2]

'Orp-Jauche'

# Sort

In [61]:
df.iloc[14:136].sort_values(by=['value', 'type_entity'], ascending=False)

       ins type_entity         entity      period   value
45   52011     Commune      Charleroi  01/01/2019  1964.7
64   53065     Commune      Quaregnon  01/01/2019  1698.9
134  62015     Commune   Beyne-Heusay  01/01/2019  1636.8
67   53082     Commune    Colfontaine  01/01/2019  1514.1
102  57096     Commune       Mouscron  01/01/2019  1439.6
..     ...         ...            ...         ...     ...
89   56088     Commune    Sivry-Rance  01/01/2019    65.2
86   56051     Commune      Momignies  01/01/2019    61.7
114  61012     Commune        Clavier  01/01/2019    58.3
81   56016     Commune         Chimay  01/01/2019    49.4
83   56029     Commune  Froidchapelle  01/01/2019    45.7

[122 rows x 5 columns]

# Saver dans un fichier

In [ ]:
df.to_csv('pandas_save.csv')

# Group by

In [63]:
df.groupby(by=['type_entity'])[['ins', 'value']].count()

                ins  value
type_entity
Arrondissement   23     23
Commune         262    262
Province          5      5
Région            1      1

In [64]:
df.groupby(by=['type_entity'])[['ins', 'value']].max()

                  ins   value
type_entity
Arrondissement  93000   833.4
Commune         93090  3518.6
Province        90000   367.9
Région           3000   215.0

In [65]:
df.groupby(by=['type_entity'])[['ins', 'value']].mean()

                         ins       value
type_entity
Arrondissement  66000.000000  286.217391
Commune         64223.480916  323.927099
Province        60000.400000  241.140000
Région           3000.000000  215.000000

In [ ]:
df.groupby(by=['type_entity'])[['ins', 'value']].mean(numeric_only=True)

In [70]:
df_copy.loc[0, 'value'] = np.nan

df_copy

       ins     type_entity           entity      period  value
0     3000          Région         Wallonie  01/01/2019    NaN
1    20002        Province   Brabant Wallon  01/01/2019  367.9
2    25000  Arrondissement         Nivelles  01/01/2019  367.9
3    25005         Commune      Beauvechain  01/01/2019  187.8
4    25014         Commune  Braine-l'Alleud  01/01/2019  764.8
..     ...             ...              ...         ...    ...
286  93018         Commune          Doische  01/01/2019   35.6
287  93022         Commune        Florennes  01/01/2019   84.3
288  93056         Commune    Philippeville  01/01/2019   59.0
289  93088         Commune         Walcourt  01/01/2019  149.1
290  93090         Commune        Viroinval  01/01/2019   46.7

[291 rows x 5 columns]

In [71]:
df_copy['value'].mean()

np.float64(319.50896551724134)

# Filtrage

In [72]:
mask = df['value'] > 150

df.loc[mask, ['ins', 'value']]

       ins  value
0     3000  215.0
1    20002  367.9
2    25000  367.9
3    25005  187.8
4    25014  764.8
..     ...    ...
277  92114  235.1
278  92137  825.7
280  92140  408.5
281  92141  174.9
282  92142  269.7

[165 rows x 2 columns]

In [75]:
df.loc[mask].groupby(by='type_entity')['ins'].count()

type_entity
Arrondissement     15
Commune           146
Province            3
Région              1
Name: ins, dtype: int64

In [76]:
df.loc[df['entity'] == 'Soignies'].groupby(by='type_entity')['ins'].count()

type_entity
Arrondissement    2
Commune           1
Name: ins, dtype: int64

# Iteration

In [77]:
for index, row in df.iterrows():
    print(row)

    if(index == 3):
        break

ins                  3000
type_entity        Région
entity           Wallonie
period         01/01/2019
value               215.0
Name: 0, dtype: object
ins                     20002
type_entity          Province
entity         Brabant Wallon
period             01/01/2019
value                   367.9
Name: 1, dtype: object
ins                     25000
type_entity    Arrondissement
entity               Nivelles
period             01/01/2019
value                   367.9
Name: 2, dtype: object
ins                  25005
type_entity        Commune
entity         Beauvechain
period          01/01/2019
value                187.8
Name: 3, dtype: object

# Extraction row/col

In [78]:
df[['ins', 'value']]

       ins  value
0     3000  215.0
1    20002  367.9
2    25000  367.9
3    25005  187.8
4    25014  764.8
..     ...    ...
286  93018   35.6
287  93022   84.3
288  93056   59.0
289  93088  149.1
290  93090   46.7

[291 rows x 2 columns]

In [79]:
df.loc[:, ['ins', 'value']]

       ins  value
0     3000  215.0
1    20002  367.9
2    25000  367.9
3    25005  187.8
4    25014  764.8
..     ...    ...
286  93018   35.6
287  93022   84.3
288  93056   59.0
289  93088  149.1
290  93090   46.7

[291 rows x 2 columns]

In [80]:
type(df['ins'])

pandas.Series

In [81]:
type(df[['ins']])

pandas.DataFrame

In [82]:
type(df.ins)

pandas.Series

Donc :

df['ins'] et df.ins vont sélectionner toutes les lignes d'une colonnes particulière.

Et df[['ins']] va retourner un tableau de la colonne ou des colonnes sélectionner.

In [83]:
df[['ins', 'value']]

       ins  value
0     3000  215.0
1    20002  367.9
2    25000  367.9
3    25005  187.8
4    25014  764.8
..     ...    ...
286  93018   35.6
287  93022   84.3
288  93056   59.0
289  93088  149.1
290  93090   46.7

[291 rows x 2 columns]

# Nettoyer

In [84]:
df.isnull().sum()

ins            0
type_entity    0
entity         0
period         0
value          0
dtype: int64

In [85]:
df.dropna()

       ins     type_entity           entity      period  value
0     3000          Région         Wallonie  01/01/2019  215.0
1    20002        Province   Brabant Wallon  01/01/2019  367.9
2    25000  Arrondissement         Nivelles  01/01/2019  367.9
3    25005         Commune      Beauvechain  01/01/2019  187.8
4    25014         Commune  Braine-l'Alleud  01/01/2019  764.8
..     ...             ...              ...         ...    ...
286  93018         Commune          Doische  01/01/2019   35.6
287  93022         Commune        Florennes  01/01/2019   84.3
288  93056         Commune    Philippeville  01/01/2019   59.0
289  93088         Commune         Walcourt  01/01/2019  149.1
290  93090         Commune        Viroinval  01/01/2019   46.7

[291 rows x 5 columns]

In [86]:
df.fillna(5)

       ins     type_entity           entity      period  value
0     3000          Région         Wallonie  01/01/2019  215.0
1    20002        Province   Brabant Wallon  01/01/2019  367.9
2    25000  Arrondissement         Nivelles  01/01/2019  367.9
3    25005         Commune      Beauvechain  01/01/2019  187.8
4    25014         Commune  Braine-l'Alleud  01/01/2019  764.8
..     ...             ...              ...         ...    ...
286  93018         Commune          Doische  01/01/2019   35.6
287  93022         Commune        Florennes  01/01/2019   84.3
288  93056         Commune    Philippeville  01/01/2019   59.0
289  93088         Commune         Walcourt  01/01/2019  149.1
290  93090         Commune        Viroinval  01/01/2019   46.7

[291 rows x 5 columns]

# Jointure

In [89]:
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": [
        "Alice",
        "Bob",
        "Charlie"
    ]
})

df2 = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "score": [
        25,
        12,
        32,
        13
    ]
})

result = pd.merge(df1, df2, on="id", how="inner")
result

   id     name  score
0   1    Alice     25
1   2      Bob     12
2   3  Charlie     32

In [90]:
pd.merge(df1, df2, on="id", how="outer")

   id     name  score
0   1    Alice     25
1   2      Bob     12
2   3  Charlie     32
3   4      NaN     13

In [92]:
pd.merge(df1, df2, how="cross")

    id_x     name  id_y  score
0      1    Alice     1     25
1      1    Alice     2     12
2      1    Alice     3     32
3      1    Alice     4     13
4      2      Bob     1     25
5      2      Bob     2     12
6      2      Bob     3     32
7      2      Bob     4     13
8      3  Charlie     1     25
9      3  Charlie     2     12
10     3  Charlie     3     32
11     3  Charlie     4     13

In [93]:
pd.merge(df1, df2, on="id", how="left")

   id     name  score
0   1    Alice     25
1   2      Bob     12
2   3  Charlie     32

In [94]:
pd.merge(df1, df2, on="id", how="right")

   id     name  score
0   1    Alice     25
1   2      Bob     12
2   3  Charlie     32
3   4      NaN     13

# Column Conversion

In [95]:
df3 = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": [
        "Alice",
        "Bob",
        "Charlie",
        "David",
    ],
    "birthdate": [
        "19901211",
        "19900302",
        "19901102",
        "19900304",
    ]
})

df3

   id     name birthdate
0   1    Alice  19901211
1   2      Bob  19900302
2   3  Charlie  19901102
3   4    David  19900304

In [98]:
df3['date-time'] = pd.to_datetime(df3['birthdate'])
df3

   id     name birthdate  timestamp
0   1    Alice  19901211 1990-12-11
1   2      Bob  19900302 1990-03-02
2   3  Charlie  19901102 1990-11-02
3   4    David  19900304 1990-03-04

In [99]:
df3['timestamp'] = pd.to_datetime(df3['birthdate']).astype(int)
df3

   id     name birthdate        timestamp
0   1    Alice  19901211  660873600000000
1   2      Bob  19900302  636336000000000
2   3  Charlie  19901102  657504000000000
3   4    David  19900304  636508800000000

In [101]:
df4 = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": [
        "Alice",
        "Bob",
        "Charlie",
        "David",
    ],
    "birthdate": [
        "11/12/1990 12:00:00.000",
        "02/03/1990 12:00:00.000",
        "02/11/1990 12:00:00.000",
        "04/03/1990 12:00:00.000",
    ]
})

df4

   id     name                birthdate
0   1    Alice  11/12/1990 12:00:00.000
1   2      Bob  02/03/1990 12:00:00.000
2   3  Charlie  02/11/1990 12:00:00.000
3   4    David  04/03/1990 12:00:00.000

In [102]:
df4['datetime'] = pd.to_datetime(df4['birthdate'], format="%d/%m/%Y %H:%M:%S.%f")
df4

   id     name                birthdate            datetime
0   1    Alice  11/12/1990 12:00:00.000 1990-12-11 12:00:00
1   2      Bob  02/03/1990 12:00:00.000 1990-03-02 12:00:00
2   3  Charlie  02/11/1990 12:00:00.000 1990-11-02 12:00:00
3   4    David  04/03/1990 12:00:00.000 1990-03-04 12:00:00